INSERT INTO tipo_operacion_produccion VALUES(01, 'Arreglo Inicial', '1' );
INSERT INTO tipo_operacion_produccion VALUES(02, 'Arreglo Subsiguiente', '1' );
INSERT INTO tipo_operacion_produccion VALUES(03, 'Tiraje', '2' );
INSERT INTO tipo_operacion_produccion VALUES(10, 'Esperando plancha', '2' );
INSERT INTO tipo_operacion_produccion VALUES(11, 'Esperando papel', '2' );
INSERT INTO tipo_operacion_produccion VALUES(12, 'Esperando tinta', '2' );
INSERT INTO tipo_operacion_produccion VALUES(13, 'Esperando aprobacion', '2' );
INSERT INTO tipo_operacion_produccion VALUES(15, 'Lavada Maquina', '1' );
INSERT INTO tipo_operacion_produccion VALUES(20, 'Reunión de mejoramiento', '3' );
INSERT INTO tipo_operacion_produccion VALUES(21, 'Reunión comité', '3' );
INSERT INTO tipo_operacion_produccion VALUES(22, 'Almuerzo o tinto', '3' );
INSERT INTO tipo_operacion_produccion VALUES(30, 'Parada por falta de energía', '1' );
INSERT INTO tipo_operacion_produccion VALUES(31, 'Parada problema plancha', '1' );
INSERT INTO tipo_operacion_produccion VALUES(33, 'Parada problema maquina', '1' );
INSERT INTO tipo_operacion_produccion VALUES(40, 'Mantenimiento programado', '1' );
INSERT INTO tipo_operacion_produccion VALUES(41, 'Maquina dañada', '1' );
INSERT INTO tipo_operacion_produccion VALUES(50, 'Sin trabajo', '3' );
INSERT INTO tipo_operacion_produccion VALUES(51, 'Otros', '0' );
